### ISSUE TITLE
建议增加解析

### ISSUE THREAD

**Issue by meininghang** [alphardex/looter#3]
和这个项目类似,国外有个大牛开发了个强大且易用的解析框架[requests_html](https://github.com/kennethreitz/requests-html),请问是否有意集成到项目中去,我觉得会更简单.

**Comment by alphardex** [comment]
本项目已经使用了lxml来解析HTML，k大的requests_html也用到了lxml，只不过find的语法利用了pyquery，本质上都是css选择器，语法大同小异，所以说我觉得没这个必要
